services: 
 demowebapp-db:
    image: mcr.microsoft.com/mssql/server
    container_name: demowebapp-db
    environment:
      MSSQL_SA_PASSWORD: "dev*5*elopmentPw"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - 1433:1433
  
 demowebapp:
    image: productive-dev/demowebapp
    build:
      context: .\
      dockerfile: Dockerfile
    container_name: demowebapp
    environment: 
            ConnectionStrings__DefaultConnection: "Server=demowebapp-db, 1433;Database=master;User ID=SA;Password=dev*5*elopmentPw"
            ASPNETCORE_HTTP_PORT: "https://+:5001"
            ASPNETCORE_URLS: "http://+:5000"
    ports:
      - 5000:5000
    depends_on:
      - demowebapp-db